- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copy NGINX configuration for the domain
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/portfolio
  notify: Restart NGINX

- name: Enable the site
  file:
    src: /etc/nginx/sites-available/portfolio
    dest: /etc/nginx/sites-enabled/portfolio
    state: link
    force: yes

- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- import_tasks: grafana.yml