- name: Configure NGINX as a reverse proxy for Next.js
  hosts: HETZNER
  become: true

  vars:
    certbot_email: rvazquezbasulto@gmail.com
    certbot_domain: rcvb.info
    ssl_email: rvazquezbasulto@gmail.com

  roles:
    - docker
    - nginx
    - certbot
    - monitoring

  