- name: Install Certbot and NGINX plugin
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present
    update_cache: yes

- name: Obtain and install SSL certificate for domain
  shell: |
    certbot --nginx -n \
      --agree-tos \
      --redirect \
      --email {{ certbot_email }} \
      -d {{ certbot_domain }} \
      -d www.{{ certbot_domain }}
  args:
    creates: /etc/letsencrypt/live/{{ certbot_domain }}/fullchain.pem
